// Generated by tools/build_narration.mjs from videos/*.vtt - do not edit.
window.KAG_NARRATION = {
 "00-interactive-demo-tour": [
  {
   "start": 0.511,
   "end": 8.635,
   "text": "Key Artifact Generator turns a requirements document into a complete project, with every key artifact generated from one Data Sheet."
  },
  {
   "start": 8.635,
   "end": 14.108,
   "text": "Sign up or log in. Each account only sees its own projects."
  },
  {
   "start": 14.108,
   "end": 22.916,
   "text": "The first screen after login: upload the requirements document. The project is created from it, and Claude starts reading."
  },
  {
   "start": 23.096,
   "end": 31.593,
   "text": "Review what Claude extracted: requirements, use cases, components and API endpoints, then open the pre-filled wizard."
  },
  {
   "start": 31.593,
   "end": 41.081,
   "text": "The New Project wizard opens already filled in from the document. Add the start date, assign real people to the team, and save the project."
  },
  {
   "start": 41.419,
   "end": 48.857,
   "text": "The Messages section lists what is still missing, how serious it is, and a button that jumps straight to the fix."
  },
  {
   "start": 49.892,
   "end": 58.485,
   "text": "Archive a finished project to hide it and restore it any time, or delete it permanently. Both sit right before Switch Project."
  },
  {
   "start": 59.336,
   "end": 66.579,
   "text": "One editable Data Sheet, in four groups and two dozen sections, feeds every generated artifact."
  },
  {
   "start": 69.574,
   "end": 76.269,
   "text": "Change a phase percentage, and the effort, schedule and milestone dates recalculate instantly."
  },
  {
   "start": 76.269,
   "end": 85.948,
   "text": "Before the work breakdown is generated, resource loading is checked. Overloaded people are flagged, and you choose to fix first or generate anyway."
  },
  {
   "start": 85.948,
   "end": 93.442,
   "text": "Twelve key artifacts are assembled from the Data Sheet, including the Analysis and Design documents written by Claude."
  },
  {
   "start": 94.353,
   "end": 101.157,
   "text": "Every artifact exports to Excel, CSV, HTML, Word or PDF."
  },
  {
   "start": 101.157,
   "end": 108.502,
   "text": "Work in the Modern, Classic or Excel layout, all on the same data, with the workbook's sheet protection."
  },
  {
   "start": 108.502,
   "end": 117.285,
   "text": "Every header has Demo and Video Demo buttons. They open in a frameless window you can minimise, maximise, or take full screen."
  },
  {
   "start": 120.099,
   "end": 128.227,
   "text": "That is Key Artifact Generator, from a requirements document to a complete, client-ready set of project artifacts."
  }
 ],
 "01-srs-first-onboarding": [
  {
   "start": 0.016,
   "end": 11.145,
   "text": "SRS-first onboarding — Sign up, upload a requirements document and let Claude create and pre-fill the project — then complete it in the wizard and generate the WBS."
  },
  {
   "start": 11.145,
   "end": 15.463,
   "text": "Create an account — each user only sees their own projects."
  },
  {
   "start": 15.463,
   "end": 23.262,
   "text": "The first screen after login: upload the SRS (.pdf, .txt or .md, up to 10 MB)."
  },
  {
   "start": 23.262,
   "end": 27.657,
   "text": "The Project Key defaults to the file name — rename it if you like."
  },
  {
   "start": 27.657,
   "end": 33.835,
   "text": "Claude reads the document and extracts requirements, design and project-setup data… (wait shortened)"
  },
  {
   "start": 34.957,
   "end": 41.682,
   "text": "Review: what Claude found — requirements, use cases, components and API endpoints."
  },
  {
   "start": 41.682,
   "end": 45.868,
   "text": "Open the New Project wizard — pre-filled from the SRS."
  },
  {
   "start": 45.868,
   "end": 53.404,
   "text": "Create Project: key, FP estimate, technology, description and scope all came from the SRS."
  },
  {
   "start": 53.404,
   "end": 56.895,
   "text": "The start date isn’t in the SRS — add it."
  },
  {
   "start": 56.895,
   "end": 62.127,
   "text": "Application Details — name, domain, category and description extracted."
  },
  {
   "start": 62.127,
   "end": 66.031,
   "text": "Hardware and software are read from the document…"
  },
  {
   "start": 66.031,
   "end": 70.556,
   "text": "Risks, constraints, assumptions and dependencies too."
  },
  {
   "start": 70.556,
   "end": 74.307,
   "text": "Functional modules identified by Claude."
  },
  {
   "start": 74.307,
   "end": 82.078,
   "text": "An SRS never names the team, so a standard role-wise team is added with placeholder people. Assign real ones:"
  },
  {
   "start": 82.078,
   "end": 88.687,
   "text": "Add what an SRS can’t know: the Kick-Off agenda, process planning and key decisions."
  },
  {
   "start": 95.007,
   "end": 99.427,
   "text": "Save Project — the wizard updates the same project in place."
  },
  {
   "start": 99.427,
   "end": 105.21,
   "text": "The project home: a Messages section lists what is still missing, each with a fix button."
  },
  {
   "start": 105.21,
   "end": 111.978,
   "text": "Before generating, resource loading is checked: each person’s WBS hours against their working time."
  },
  {
   "start": 111.978,
   "end": 118.987,
   "text": "A JIRA-ready WBS: tasks per person with dates and estimates — download as Excel or CSV."
  },
  {
   "start": 118.987,
   "end": 124.306,
   "text": "The Analysis and Design documents were written by Claude from the SRS."
  },
  {
   "start": 126.561,
   "end": 137.284,
   "text": "Done: from SRS to WBS — Project created from the requirements document, completed in the wizard, team assigned and WBS generated."
  }
 ],
 "02-classic-editor": [
  {
   "start": 0.041,
   "end": 9.489,
   "text": "Classic editor (Web App layout) — The full Data Sheet as sections with completion bars, the Messages panel, project summary and every artifact."
  },
  {
   "start": 9.489,
   "end": 16.144,
   "text": "Home: completion, effort, FTE and WBS tasks at a glance — plus Messages."
  },
  {
   "start": 16.144,
   "end": 20.502,
   "text": "Every Data Sheet section with its completion — click one to edit it."
  },
  {
   "start": 20.502,
   "end": 25.902,
   "text": "Risks — rows extracted from the SRS, editable inline."
  },
  {
   "start": 25.902,
   "end": 32.915,
   "text": "HR plan — roles, people, % contribution and dates (feeds the WBS and resource loading)."
  },
  {
   "start": 32.915,
   "end": 38.935,
   "text": "Project Summary: effort per phase, schedule and milestone dates — computed live."
  },
  {
   "start": 38.935,
   "end": 45.985,
   "text": "Artifacts open as previews — export each as Excel, CSV, HTML, Word or PDF."
  },
  {
   "start": 45.985,
   "end": 52.303,
   "text": "Switch between the Modern, Excel and Web App layouts any time — same data."
  }
 ],
 "03-modern-layout": [
  {
   "start": 0.006,
   "end": 8.046,
   "text": "Modern layout — A sidebar of sections with completion badges, accordion or tab editing, and a live project summary."
  },
  {
   "start": 8.046,
   "end": 12.531,
   "text": "Messages at the top; sections on the left with their completion."
  },
  {
   "start": 12.531,
   "end": 17.857,
   "text": "Edit any section in place — Software, extracted from the SRS."
  },
  {
   "start": 17.857,
   "end": 22.508,
   "text": "Prefer tabs? Switch between accordion and tab editing."
  },
  {
   "start": 22.508,
   "end": 28.342,
   "text": "Project summary: overall and per-group completion, effort and schedule."
  },
  {
   "start": 29.012,
   "end": 36.255,
   "text": "IPP-Scope Management — scope, constraints, assumptions, dependencies and modules."
  }
 ],
 "04-excel-layout": [
  {
   "start": 0.007,
   "end": 10.617,
   "text": "Excel layout — A faithful replica of Key Artifact Generator-V1.0.xls: the Data Sheet, sheet tabs, macros as buttons and sheet protection."
  },
  {
   "start": 10.617,
   "end": 16.052,
   "text": "The Data Sheet, exactly like the workbook — jump to a section from the left panel."
  },
  {
   "start": 16.052,
   "end": 20.461,
   "text": "Project-Data → Risks (the workbook’s GoToDataSection macro)."
  },
  {
   "start": 20.461,
   "end": 24.73,
   "text": "Sheet tabs are the generated artifacts — the Kick-Off deck…"
  },
  {
   "start": 24.73,
   "end": 28.85,
   "text": "…the Application Initiation Note, renamed per project…"
  },
  {
   "start": 28.85,
   "end": 32.326,
   "text": "…and every Internal Project Plan section."
  },
  {
   "start": 32.326,
   "end": 40.397,
   "text": "WBS For JIRA — generated from the HR plan and task templates (the GenWBS2 macro)."
  },
  {
   "start": 40.397,
   "end": 45.811,
   "text": "Protect / Unprotect toggles read-only mode, like the sheet-protection radios."
  },
  {
   "start": 45.811,
   "end": 51.184,
   "text": "Copy To Desktop downloads the chosen artifact as an Excel file."
  }
 ],
 "05-manage-projects": [
  {
   "start": 0.005,
   "end": 9.31,
   "text": "Managing projects — Create a project manually, switch between projects, archive one (restorable) or delete it permanently."
  },
  {
   "start": 9.31,
   "end": 14.646,
   "text": "The start screen lists your projects — or create one manually without an SRS."
  },
  {
   "start": 14.646,
   "end": 19.305,
   "text": "The same step-by-step wizard, with a blank draft."
  },
  {
   "start": 22.217,
   "end": 27.731,
   "text": "On the project home, Archive project and Delete project sit right before Switch Project."
  },
  {
   "start": 27.731,
   "end": 31.684,
   "text": "Archiving hides the project but keeps all its data."
  },
  {
   "start": 31.684,
   "end": 37.448,
   "text": "Archived projects are listed on the start screen — Restore brings one back."
  },
  {
   "start": 39.678,
   "end": 44.538,
   "text": "Delete is permanent — the dialog lists what goes and offers Archive instead."
  },
  {
   "start": 44.538,
   "end": 51.417,
   "text": "Gone — the project and all its data. Only the owner can archive or delete a project."
  }
 ]
};
