// Builds ../narration.js from ../videos/*.vtt: the narration cues embedded as
// JavaScript, because browsers refuse to load .vtt <track> files for a page
// opened from disk (file://). presentation.js turns them back into subtitle
// tracks and the clickable transcripts. Run after re-recording the videos.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const videos = path.join(here, '..', 'videos');
const secs = (s) => { const [h, m, x] = s.split(':'); return Math.round((+h * 3600 + +m * 60 + +x) * 1000) / 1000; };
const out = {};
for (const f of fs.readdirSync(videos).filter((x) => x.endsWith('.vtt')).sort()) {
  const blocks = fs.readFileSync(path.join(videos, f), 'utf8').replace(/\r/g, '').split(/\n\n+/).slice(1);
  out[f.replace(/\.vtt$/, '')] = blocks.map((b) => {
    const lines = b.trim().split('\n');
    const timing = lines.find((l) => l.includes('-->'));
    if (!timing) return null;
    const [start, end] = timing.split('-->').map((x) => secs(x.trim()));
    return { start, end, text: lines.slice(lines.indexOf(timing) + 1).join(' ') };
  }).filter(Boolean);
}
const js = '// Generated by tools/build_narration.mjs from videos/*.vtt - do not edit.\n' +
  'window.KAG_NARRATION = ' + JSON.stringify(out, null, 1) + ';\n';
fs.writeFileSync(path.join(here, '..', 'narration.js'), js);
console.log('narration.js:', Object.entries(out).map(([k, v]) => `${k} (${v.length} cues)`).join(', '));
