// Export service - replicates "Copy Artifact To Desktop" (CopyArtifactToDesktop macro).
// The macro copied a sheet's values+formats into a new workbook and saved
// "<ProjectName>-<SheetName>.xls" on the desktop. Here we stream an Excel-compatible
// file (HTML table .xls or CSV) so the browser downloads it.

function esc(v) {
  if (v === null || v === undefined) return '';
  return String(v)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>');
}

/**
 * rowsToXls - rows: array of arrays. Each cell can be a value or
 * {v, header, title, colspan, bold}
 */
function rowsToXls(sheetName, rows) {
  const body = rows.map((row) => {
    const tds = row.map((cell) => {
      const c = (cell && typeof cell === 'object' && !Array.isArray(cell)) ? cell : { v: cell };
      const tag = c.header ? 'th' : 'td';
      const style = [
        c.title ? 'font-size:16pt;font-weight:bold;background:#1F497D;color:#fff;' : '',
        c.header ? 'background:#DCE6F1;font-weight:bold;border:1px solid #95B3D7;' : 'border:1px solid #D9D9D9;',
        c.bold ? 'font-weight:bold;' : ''
      ].join('');
      const span = c.colspan ? ` colspan="${c.colspan}"` : '';
      return `<${tag}${span} style="${style}">${esc(c.v)}</${tag}>`;
    }).join('');
    return `<tr>${tds}</tr>`;
  }).join('\n');

  return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel">
<head><meta charset="UTF-8">
<!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>
<x:Name>${esc(sheetName).slice(0, 31)}</x:Name>
<x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions>
</x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->
<style>td,th{font-family:Arial;font-size:10pt;vertical-align:top;}</style>
</head><body><table>${body}</table></body></html>`;
}

function rowsToCsv(rows) {
  return rows.map((row) => row.map((cell) => {
    const v = (cell && typeof cell === 'object' && !Array.isArray(cell)) ? cell.v : cell;
    const s = v === null || v === undefined ? '' : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  }).join(',')).join('\r\n');
}

/**
 * rowsToHtml - standalone styled HTML document (used for "Download HTML"
 * and, with an application/msword content type, for "Download Doc" -
 * MS Word opens HTML documents natively).
 */
function rowsToHtml(title, rows) {
  const body = rows.map((row) => {
    if (!row.length) return '<tr><td class="spacer" colspan="10"></td></tr>';
    const tds = row.map((cell) => {
      const c = (cell && typeof cell === 'object' && !Array.isArray(cell)) ? cell : { v: cell };
      const tag = c.header ? 'th' : 'td';
      const cls = [c.title ? 'title' : '', c.bold ? 'bold' : ''].filter(Boolean).join(' ');
      const span = c.colspan ? ` colspan="${c.colspan}"` : '';
      return `<${tag}${span}${cls ? ` class="${cls}"` : ''}>${esc(c.v)}</${tag}>`;
    }).join('');
    return `<tr>${tds}</tr>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${esc(title)}</title>
<style>
  body { font-family: "Segoe UI", Arial, sans-serif; font-size: 10.5pt; color: #0f172a; margin: 28px; }
  h1 { color: #1F497D; font-size: 16pt; border-bottom: 3px solid #4f81bd; padding-bottom: 4px; }
  table { border-collapse: collapse; width: 100%; }
  td, th { border: 1px solid #d9e2ec; padding: 5px 8px; vertical-align: top; text-align: left; }
  th { background: #dce6f1; color: #1F497D; font-size: 9pt; text-transform: uppercase; letter-spacing: .4px; }
  td.title { font-size: 14pt; font-weight: bold; background: #1F497D; color: #fff; }
  td.bold { font-weight: bold; background: #eef2ff; color: #1F497D; }
  td.spacer { border: none; height: 10px; }
</style>
</head>
<body>
<h1>${esc(title)}</h1>
<table>${body}</table>
<p style="color:#64748b;font-size:8.5pt">Generated by Key Artifact Generator</p>
</body></html>`;
}

/**
 * rowsToPdf - renders the artifact rows to a PDF buffer (pdfkit).
 * Single-cell rows become paragraphs (title/bold aware); multi-cell rows are
 * laid out as table rows with equal column widths and wrapped text.
 */
function rowsToPdf(title, rows) {
  const PDFDocument = require('pdfkit');
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40, info: { Title: title } });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      const left = 40;
      const usable = doc.page.width - 80;
      const ensureSpace = (h) => {
        if (doc.y + h > doc.page.height - 40) { doc.addPage(); doc.y = 40; }
      };
      const clean = (v) => String(v ?? '').replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/–|—/g, '-');

      doc.font('Helvetica-Bold').fontSize(16).fillColor('#1F497D').text(clean(title), left, doc.y, { width: usable });
      doc.moveTo(left, doc.y + 2).lineTo(left + usable, doc.y + 2).lineWidth(1.5).strokeColor('#4f81bd').stroke();
      doc.y += 10;

      for (const row of rows) {
        const cells = row.map((c) => (c && typeof c === 'object' && !Array.isArray(c)) ? c : { v: c });
        if (!cells.length) { doc.y += 6; continue; }

        if (cells.length === 1) {
          const c = cells[0];
          const isTitle = !!c.title;
          const bold = isTitle || c.bold;
          doc.font(bold ? 'Helvetica-Bold' : 'Helvetica')
            .fontSize(isTitle ? 12.5 : 9.5)
            .fillColor(bold ? '#1F497D' : '#111111');
          const text = clean(c.v) || ' ';
          const h = doc.heightOfString(text, { width: usable });
          ensureSpace(h + (isTitle ? 12 : 4));
          if (isTitle) doc.y += 6;
          doc.text(text, left, doc.y, { width: usable });
          doc.y += 3;
          continue;
        }

        const isHeader = cells.some((c) => c.header);
        const colW = usable / cells.length;
        doc.font(isHeader ? 'Helvetica-Bold' : 'Helvetica').fontSize(8);
        const texts = cells.map((c) => clean(c.v) || ' ');
        let rowH = 0;
        texts.forEach((t) => { rowH = Math.max(rowH, doc.heightOfString(t, { width: colW - 6 })); });
        ensureSpace(rowH + 6);
        const y = doc.y;
        if (isHeader) {
          doc.rect(left, y - 2, usable, rowH + 5).fillColor('#dce6f1').fill();
        }
        texts.forEach((t, i) => {
          doc.fillColor(isHeader ? '#1F497D' : '#111111')
            .text(t, left + i * colW + 3, y, { width: colW - 6 });
        });
        doc.y = y + rowH + 4;
        doc.x = left;
        doc.moveTo(left, doc.y - 2).lineTo(left + usable, doc.y - 2).lineWidth(0.5).strokeColor('#dddddd').stroke();
      }

      doc.fontSize(7.5).fillColor('#64748b')
        .text('Generated by Key Artifact Generator', left, doc.page.height - 34, { width: usable });
      doc.end();
    } catch (e) { reject(e); }
  });
}

module.exports = { rowsToXls, rowsToCsv, rowsToHtml, rowsToPdf };
